### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by darksnakezero** [dennybritz/rnn-tutorial-rnnlm#5]
I would like to use this code for some project at the FAU (Friedrich-Alexander-University Erlangen-Nürnberg, Germany).

Without a license, I can use the code but may not redistribute it. I d like to have it graded, so I need to give it to the University. This may be forbidden without a license.

All in all, I would need a written text saying I can use it for this purpose, or a license.

Currently I am adjusting the code to learn a language character-based.

Thanks in advance,
DSZ

**Comment by dennybritz** [comment]
Can you submit a pull request with an Apache license? I'll merge it.

**Comment by darksnakezero** [comment]
Done.

Tank you very much.
